---
title: "tidy-tuesday-rladies"
format: html
---

```{r}
#| label: libraries
library(tidyverse)
library(ggthemes)
library(tidytuesdayR)

# chocolate ratings
tuesdata_ch <- tidytuesdayR::tt_load(2022, week = 3)

chocolate_df <- tuesdata_ch$chocolate
```

```{r}
chocolate <- chocolate_df %>% 
  separate(ingredients, into = c("n_ingredients", "ingredient_list"),sep = "-") %>% 
  mutate(n_ingredients = as.numeric(n_ingredients),
       ingredient_list = str_trim(ingredient_list),
       cocoa_percent = as.numeric(str_remove(cocoa_percent, "%")),
       most_memorable_characteristics = str_split(tolower(most_memorable_characteristics),",")) %>% 
  unnest(most_memorable_characteristics) %>% 
  mutate(characteristics = str_trim(most_memorable_characteristics))

chocolate %>% 
  count(characteristics)

chocolate %>% 
  mutate(cocoa_pct_bin = cut(cocoa_percent, c(-Inf,65,70,75,80,100),
                             labels = c("0-65%","66-70%","71-75%","76-80%","81-100%"))) %>% 
  group_by(cocoa_pct_bin) %>% 
  summarise(n = n_distinct(characteristics),
            n_chocolates = n_distinct(ref)) %>% 
  ggplot(aes(x = cocoa_pct_bin,
            fill = cocoa_pct_bin,
            y = n_chocolates)) +
  geom_col(position = "dodge")  +
  geom_text(aes(label = round(n/n_chocolates,2)), vjust = 1.5) +
  scale_y_continuous(breaks = seq(0,1000,100)) + 
  scale_fill_brewer(type = "sequential",palette = "Oranges", direction = 1,
                    guide  = "none") + 
  theme_minimal() + 
  labs(title = "Number of chocolates per cocoa group",
       subtitle = "Text shows: Average unique characteristics",
       x = NULL,
       fill = NULL,
       y = NULL) +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text = element_text(face = "plain", size = rel(0.75)),
        axis.title = element_text(face = "plain", size = rel(0.9), 
                                  color = "gray20", 
                                  hjust = 0),
        plot.title.position = "plot",
        axis.text.x.bottom = element_text(hjust = 0.8, debug = F),
        text = element_text(color ="gray36"),
        plot.title = element_text(face = "bold", size = rel(1.2), color = "black"),
        plot.subtitle = element_text(face = "bold", size = rel(1.1),
                                       margin = margin(c(-5,0,5,0)),color = "gray20"))
```